server:
  port: 8081
spring:
  application:
    name: hmdp  # 应用名称
  profiles:
    active: dev # 默认开发环境
  datasource:
    driver-class-name: ${hmdp.datasource.driver-class-name}
    url: jdbc:mysql://${hmdp.datasource.host}:${hmdp.datasource.port}/${hmdp.datasource.database}?useSSL=false&serverTimezone=UTC
    username: ${hmdp.datasource.username}
    password: ${hmdp.datasource.password}
  redis:
    host: ${hmdp.redis.host} #  地址
    port: ${hmdp.redis.port} # 端口
    password: ${hmdp.redis.password} # 密码
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    database: ${hmdp.redis.database}  # 使用数据库
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 显示SQL
logging:
  level:
    com.hmdp: debug